import type { Metadata } from "next";
import { Rowdies, Open_Sans } from 'next/font/google';
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

// app/layout.tsx or any component


const rowdies = Rowdies({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  display: 'swap',
  variable: '--font-rowdies',
});

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'],
  display: 'swap',
  variable: '--font-open-sans',
});


export const metadata: Metadata = {
  title: "Miku Mockup Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html>
      <body
        className={`${rowdies.variable} ${openSans.variable}`}>
        <>
        <Navbar />
        {children}
        <Footer />
        </>
      </body>
      </html>
  );
}
